### ISSUE TITLE
Doesn't work with Grid + Gauge Cards

### ISSUE THREAD

**Issue by valantur** [RossMcMillan92/lovelace-collapsable-cards#11]
I have a grid card with 6 gauge cards in it, showing the air quality index of 6 different areas around my city. When wrapping all of this inside the collapsable card, the sensors don't display their value. The gauge is OK (as green or red as it has to be based on the entity's value) but the value is not displayed.

<img width="544" alt="AQI" src="https://user-images.githubusercontent.com/2516392/123529566-69a0e780-d6a6-11eb-85c1-98543aeb10db.png">

**Comment by kmlucy** [comment]
I believe this was fixed by https://github.com/RossMcMillan92/lovelace-collapsable-cards/pull/16. 

![image](https://user-images.githubusercontent.com/13952475/147758343-e0f7babb-c035-4d1f-91da-cfbdc4cabaac.png)

@valantur Can you confirm?

**Comment by valantur** [comment]
Works great now! thank you very much!
