### ISSUE TITLE
Default collapsed mobile only

### ISSUE THREAD

**Issue by kmlucy** [RossMcMillan92/lovelace-collapsable-cards#2]
Would it be possible to have a setting so the cards are collapsed by default only on mobile, and expanded by default on a computer?

**Comment by haberda** [comment]
I agree this would be nice. 

I think even better would be a conditional where if some condition is met the card could be expanded. For example: a light is under the collapsed card, if light is on -> card expanded, if light is off -> collapsed. We could define the conditions just like the conditional card in the default install. 

Right now, I get around this by hiding the collapsed card with a conditional card that then displays what I want.
