### ISSUE TITLE
Inherit CSS from Dashboard

### ISSUE THREAD

**Issue by jcgoette** [RossMcMillan92/lovelace-collapsable-cards#4]
Thoughts on this? Do you accept PRs?

**Comment by seanomat** [comment]
Are you trying to address the fact, that the default color of the title seems to be white, which is "invisible" in the default theme and any other theme that has a white background? 
Would be great, if this card would respect the colors of the current theme.

**Comment by RossMcMillan92** [comment]
Yes, feel free to submit a PR. In the meantime, you can use the buttonStyle property to change the color.

**Comment by RossMcMillan92** [comment]
Nevermind, I have made the change.

**Comment by jcgoette** [comment]
When do you plan to add to latest release?

**Comment by RossMcMillan92** [comment]
It was added in May

**Comment by jcgoette** [comment]
[I think since you created an initial release, you have to create a new release with the tag the commit is on.](https://hacs.xyz/docs/publish/plugin#github-releases-optional)

**Comment by TKpizza** [comment]
> Yes, feel free to submit a PR. In the meantime, you can use the buttonStyle property to change the color.

I'm trying to figure out how to do that can you provide some assistance?
